sudo: required

language: java

services:
  - docker

before_install:
- docker pull jenkins/jenkins:lts

script:
- docker build -t novsyama/jenkins-japanese:lts --build-arg VCS_REF=`git rev-parse --short HEAD` .
- docker images

deploy:
  provider: script
  script: bash push
  on:
    branch: master

notifications:
  email: false
