sudo: required

language: java

services:
  - docker

before_install:
- docker pull jenkins/jenkins:lts

script:
- bash ./hooks/build

deploy:
  provider: script
  script: bash push
  on:
    branch: master

notifications:
  email: false
