#!/bin/bash

TAG=`date +%Y%m%d`
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag novsyama/jenkins-japanese:lts novsyama/jenkins-japanese:${TAG}
docker push novsyama/jenkins-japanese:${TAG}
docker push novsyama/jenkins-japanese:lts
